### ISSUE TITLE
_key undefined in dynamo.

### ISSUE THREAD

**Issue by mariscorenett** [Macrometacorp/docs#40]
Creating a table in dynamo with _key as partition key and when executing the below query all the _key value is undefined for all the records.

**Comment by macrochrissie** [comment]
reference here: https://macrometa.com/docs/demos/credit-card-fraud/#create-customers

**Comment by jamesm-macrometa** [comment]
Hi @mariscorenett  - thanks for bringing this issue to our attention.  We appreciate your feedback.

Can you please provide a bit more context about the issue you're having, such as the steps you followed to create the table and run the query?

Thanks!
James Maxwell
Technical Writer

**Comment by MMSlobs** [comment]
HI @mariscorenett,

Thank you for using our product, we are informing you that we have reported the bug and engineering is working on fixing the issue.

Best regards,
Slobodan Mijatovic
Macrometa Support Engineer

**Comment by Luba89** [comment]
HI @mariscorenett,

We want to let you know that the issue is fixed. Thank you for bringing this to our attention.
Have a great day!

Best regards,
Ljubisav
Macrometa Support Engineer
