### ISSUE TITLE
404 on https://macrometa.com/troubleshooting/

### ISSUE THREAD

**Issue by SalvaFiorenza8-Macrometa** [Macrometacorp/docs#68]
While creating my account I stumbled into a page that told me to wait (sorry I didn't take any screenshot) and that page contained a link to `https://macrometa.com/troubleshooting/` but when I clicked on it, I only found a 404 page.

![image](https://user-images.githubusercontent.com/106981293/172231086-e9f35b82-4c95-431e-8278-e6223e3b9028.png)

I'm accessing that link from Google Chrome Version 102.0.5005.61 (Official Build) (x86_64) for mac.

**Comment by jamesm-macrometa** [comment]
I'm pretty sure that troubleshooting URL is a dead link.

@macrochrissie Do you think you can look into this?  It appears to be related to a message during the account creation screen.  I assume this message is on a webpage and not part of the docs.

@SalvaFiorenza8-Macrometa Can you please try and find the page you saw that included the link, and post it here?  That'll help Chrissie identify the problem page 🙂 

cc @diana-macrometa

**Comment by SalvaFiorenza8-Macrometa** [comment]
Sure, I can try to create a new account to locate the page that has the link

**Comment by SalvaFiorenza8-Macrometa** [comment]
This is a screenshot of my whole screen during the account creation and the page with the dead link:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/106981293/172905963-355c4618-81c8-4e93-84bb-7d8884150259.png">
and this is the link:
> https://auth.paas.macrometa.io/verify?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvd2lkZWQ0NjVAbXVzZXpvby5jb20iLCJ1cmwiOiJodHRwczovL2dkbi5wYWFzLm1hY3JvbWV0YS5pby8iLCJzaWdudXBfYXR0cmlidXRpb24iOiJNYWNyb21ldGEiLCJpYXQiOjE2NTQ3OTQ4MzYsImV4cCI6MTY1NDc5NjYzNn0.U0yOo7YD89PDazt4pgY5qiby07TUJjW-aMRnIHsYy3A

**Comment by jamesm-macrometa** [comment]
Posted a request in our internal website channel to get this resolved.  Closing this issue.

Thanks again @SalvaFiorenza8-Macrometa !
