### ISSUE TITLE
Issue trying to follow quickstart guide

### ISSUE THREAD

**Issue by SalvaFiorenza8-Macrometa** [Macrometacorp/docs#69]
I was following the steps at the [quickstart guide](https://macrometa.com/docs/quickstart/) and when I was trying to run the `Remove Contact` and `Update Contact` queries, I got the following errors:

![image](https://user-images.githubusercontent.com/106981293/172235027-4ff8dcb7-5831-462d-b258-b63ba1c7804f.png)

![image](https://user-images.githubusercontent.com/106981293/172235170-1c056ef1-ab5b-4467-bcd8-155242180fee.png)

I was following the tutorial using Google Chrome Version 102.0.5005.61 (Official Build) (x86_64)

**Comment by jamesm-macrometa** [comment]
Thanks for the heads up @SalvaFiorenza8-Macrometa - @diana-macrometa and myself are working on revising the Quickstart guides and will incorporate these comments into our review.

**Comment by diana-macrometa** [comment]
@elof and @astrotars  - I think the issue here is that there are no values in the base query. However, I was unable to get this example to work even when I entered values. Can you give me a syntax to enter in the C8QL editor that will work with no errors? 

**Name:** updateContact
```sql
UPDATE @_key WITH { firstname:@firstName, 
                    lastname:@lastName, 
                    email:@email} 
IN addresses
```
