### ISSUE TITLE
Quickstart guide references API Usage button, but looks like the button was renamed to API Endpoint

### ISSUE THREAD

**Issue by SalvaFiorenza8-Macrometa** [Macrometacorp/docs#70]
When following the [quickstart guide](https://macrometa.com/docs/quickstart/) the step 4 required me to click on the `API Usage` button, but I was unable to find a button named like that, experimenting with the buttons I found that the `API Endpoint` appears to have the same function, which makes me think that the buttons was renamed and that the quickstart guide maybe needs to be updated to match the application.

![image](https://user-images.githubusercontent.com/106981293/172237123-e365ed9f-e020-4b73-9215-19c88da3da69.png)

![image](https://user-images.githubusercontent.com/106981293/172236887-8b232da5-c873-4ef5-9ae4-2094aabb02e1.png)

**Comment by jamesm-macrometa** [comment]
Thanks for the heads up @SalvaFiorenza8-Macrometa - @diana-macrometa and myself are working on revising the Quickstart guides and will incorporate these comments into our review.
