### ISSUE TITLE
Wording in quickstart guide

### ISSUE THREAD

**Issue by SalvaFiorenza8-Macrometa** [Macrometacorp/docs#72]
When reading the[ quickstart guide](https://macrometa.com/docs/quickstart/), I noticed this sentence `First things first, if you don't already have a Macrometa account go create a free one and mosey on back.` I found really curious the last part `mosey on back` I haven't heard that expression before (English is not my first language), after searching for it I understand that `monsey` means something like wander about unhurried, I haven't found anything on `mosey on back`, so I don't know if the whole phrase has a different meaning. From following the quickstart guide I learned that the app takes a couple of minutes to setup the account, So I can infer that the sentence means that the user can relax while their account is configured and then return back to continue the guide. If I'm correct what do you think of using a simpler wording? Like `First things first, if you don't have a Macrometa account already, go and create one for free. This could take a couple of minutes, so feel free to grab a snack and then come back to this guide.`, I'm mostly talking from my personal opinion as a non-native speaker. Thanks!

**Comment by jamesm-macrometa** [comment]
Hi @SalvaFiorenza8-Macrometa - thanks for the feedback!  @diana-macrometa and myself are in the process of revising and rewriting the Quickstart content to remove the exact kind of language you pointed out.  You're right that it's confusing and does not belong in technical documentation.

Closing this issue as a PR will be forthcoming to resolve this.
